### ISSUE TITLE
Two songs are playing at the same time and "Pause, Stop and Play" button not working properly after I changed app's setting to "Wait until finished"

### ISSUE THREAD

**Issue by sagorahmed** [michpohl/Loopy#5] opened 2019-05-07 11:17 UTC
#### Expected behavior
I expected that the player would move to my selected next song after finishing the first song without playing two songs at the same time. 

#### Actual behavior
I changed this app's setting to "wait until finished" after then this app is playing two songs at the same time and "Pause" "Stop" "Play" button doesn't work as well.

#### How to reproduce
1. Open the app.
2. Go to "Browse Music Library" and select a few songs to add on your selection dashboard.
3. Then go to this app's options and click on "Change app settings".
4. Select "Wait until finished" under the "Loop switching behavior" and save it.
5. Then get back to your player's dashboard and play a song. [The app will indicate this song in red color]
6. Tap on another one and this song will indicate as green color.
7. Notice that your first selected(Red color) song is playing. After that, fast forward this song or let this song to the end.
8. After finishing your song, the player will move to the green song.
9. Carefully hear that both songs are playing at the same moment. You can also click on "Pause, Stop, Play" to notice some weird behavior of this app.

* Browser/App version: V0.9
* Operating system: Android 6.0.1

#### Recording Of The Bug
![bb](https://media.giphy.com/media/XFprxXYKN12XLAqM8q/giphy.gif)

**Comment by michpohl** [comment] 2019-06-10 16:05
Thank you for submitting this. So far I am unable to reproduce the error, despite the very detailed description you gave. As soon as I find time, I will revisit this again and see if I can figure it out. Maybe you can provide what kind of device you were using to use the app? Thank you!

**Comment by sagorahmed** [comment] 2019-06-10 17:08
I was used Samsung A5 when these issues occurred. 
Hope you will fix these issues and make this app bug free. 
Thanks

**Comment by michpohl** [comment] 2019-06-10 17:15
Oh, of course! But please be aware that this is a project I do in my free time, so I do not get to spend time on it very often. Will look at it as soon as I can though!

**Comment by michpohl** [comment] 2019-09-15 21:32
update: Just to let you know that I am still working on this - really sorry, but I just don't find enough time for the project to get stuff doe faster. I am in the middle of migrating the whole thing to using oboe for playback and AndroidX for the whole appearance. 
This means quite a bit of the app has to be refactored, so it will still take time - but I will address this and the other issues in the process. Everything should be resolved when I finally release 1.0 of this litthe project.

**Comment by michpohl** [comment] 2021-07-04 06:01
This should be resolved with the release of Loopy 2

**Closed as completed by michpohl** 2021-07-04 06:01 UTC
Labels: bug
